#!/bin/sh

brew update && brew upgrade git python3 pipenv node youtube-dl ruby openssl curl wget mongodb kubectl crystal ; brew upgrade ffmpeg --with-chromaprint --with-fdk-aac --with-libass --with-librsvg --with-libsoxr --with-libssh --with-tesseract --with-libvidstab --with-opencore-amr --with-openh264 --with-openjpeg --with-openssl --with-rtmpdump --with-rubberband --with-sdl2 --with-snappy --with-tools --with-webp --with-x265 --with-xz --with-zeromq --with-zimg --with-ffplay --with-freetype --with-libquvi --with-libvorbis --with-libvpx --with-opuS

npm install -g npm@latest
npm update -g nodemon
#https://arui.tech/en/why-locally-install-is-much-better-than-globally-in-npm/
#npm update -g nodemon request lodash yargs wepy-cli typescript coffeescript http-server vue d3 three p5 periodic-table

#todo: macos upgrade pip3
#sudo pip install --upgrade pip pip3
#Collecting pip3
#  Could not find a version that satisfies the requirement pip3 (from versions: )
#No matching distribution found for pip3

#https://github.com/Homebrew/legacy-homebrew/issues/50607
#python3 -m pip install -U --force-reinstall pip

python3 -m pip install -U pip
#$which pip3
#/usr/local/bin/pip3
#$pip3 -V
#pip 10.0.1 from /usr/local/lib/python3.6/site-packages/pip (python 3.6)
#$pip -V
#pip 10.0.1 from /usr/local/lib/python3.6/site-packages/pip (python 3.6)

#https://stackoverflow.com/questions/2720014/upgrading-all-packages-with-pip?rq=1
#pip list --outdated --format=freeze | tee pip_before_upgrade.txt | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U

#todo: pip3 install --upgrade virtualenvwrapper virtualenv  #virtualenv is unnecessary because of pipenv, what about virtualenvwrapper?

#https://www.tensorflow.org/install/install_mac

#pip3 install --upgrade tensorflow
#Collecting tensorflow
#  Could not find a version that satisfies the requirement tensorflow (from versions: )
#No matching distribution found for tensorflow

#pip install --upgrade  tensorflow
#Requirement already up-to-date: tensorflow in /usr/local/lib/python2.7/site-packages (1.10.1)

#pip2 install --upgrade  tensorflow
#Requirement already up-to-date: tensorflow in /usr/local/lib/python2.7/site-packages (1.10.1)

# pip == pip2 ?

sudo pip3 install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.10.1-py3-none-any.whl
pip3 install --upgrade PySocks Flask keras six cppman itchat pylint pip

#lldb on MacOS uses python2's six?
pip2 install --upgrade PySocks Flask tensorflow keras six cppman itchat pylint pip

#$ZSH/tools/upgrade.sh #Permission denied
#https://github.com/robbyrussell/oh-my-zsh/issues/4078
#upgrade_oh_my_zsh () {
	env ZSH=$ZSH sh $ZSH/tools/upgrade.sh
#}
