#!/bin/bash

#invoke as: su -c ./efi_vrboxkey_fedora
echo $(uname -r)
#cd /home/r/vboxdrv_key

openssl req -new -x509 -newkey rsa:2048 -keyout vboxdrv_X.509.priv -outform DER -out vboxdrv_X.509.der -nodes -days 36500 -subj "/CN=vboxdrv_X.509_Org/"

/usr/src/kernels/$(uname -r)/scripts/sign-file sha256 ./vboxdrv_X.509.priv ./vboxdrv_X.509.der $(modinfo -n vboxdrv)

echo -e "Prsvrr\nPrsvrr" | mokutil --import vboxdrv_X.509.der
