#!/bin/sh

rm -rf /home/r/.cache /home/r/.Trash

# cp shtdwnscrpt /etc/rc.d/init.d
#Doesn't work!
# ln -s /etc/rc.d/init.d/shtdwnscrpt /etc/rc.d/rc0.d/K99shtdwnscrpt
# ln -s /etc/rc.d/init.d/shtdwnscrpt /etc/rc.d/rc6.d/K99shtdwnscrpt

