#!/bin/sh

gnome-terminal --maximize --tab-with-profile=Default --tab-with-profile=Default --working-directory=/mnt/1 --tab-with-profile=Default --working-directory=/mnt/0 --tab-with-profile=Default --working-directory=/mnt/0/gthb/noncode --tab-with-profile=Default --working-directory=/mnt/0/gthb/exercise

#google-chrome --ssl-version-min=tls1 --incognito http://ferd.ca/queues-don-t-fix-overload.html https://goagent.github.io http://speakingjs.com/es5/index.html 

firefox --ssl-version-min=tls1 -private https://goagent.github.io https://www.torproject.org http://chinadigitaltimes.net/chinese/2015/02/%E7%BF%BB%E5%A2%99-ghost-assassin%EF%BC%9A%E7%BF%BB%E5%A2%99%E4%B8%8E%E5%8C%BF%E5%90%8D%E4%B8%8E%E4%BF%A1%E6%81%AF%E5%AE%89%E5%85%A8%E7%A7%91%E6%99%AE%E6%96%87%E9%93%BE%E6%8E%A5%E9%9B%86%E5%90%88 https://startpage.com
