#!/bin/sh

gnome-terminal --maximize --tab-with-profile=Default --working-directory=~ --tab-with-profile=Default --working-directory=/mnt/1/wbst --tab-with-profile=Default --working-directory=/mnt/0/gthb/noncode --tab-with-profile=Default --working-directory=/mnt/0/gthb/exercise

#google-chrome --ssl-version-min=tls1 --incognito http://ferd.ca/queues-don-t-fix-overload.html https://goagent.github.io http://speakingjs.com/es5/index.html 

firefox --ssl-version-min=tls1.2 -private herbsutter.com https://github.com/kjellkod/g3log https://progit.org/ https://www.google.ca https://www.howsmyssl.com/ &

vlc

