#!/bin/sh

gnome-terminal --maximize --tab-with-profile=Default --tab-with-profile=Default --working-directory=/mnt/1 --tab-with-profile=Default --working-directory=/mnt/0 --tab-with-profile=Default --working-directory=/mnt/0/gthb/noncode --tab-with-profile=Default --working-directory=/mnt/0/gthb/exercise

#google-chrome --ssl-version-min=tls1 --incognito http://ferd.ca/queues-don-t-fix-overload.html https://goagent.github.io http://speakingjs.com/es5/index.html 

firefox --ssl-version-min=tls1 -private https://goagent.github.io https://www.torproject.org http://chinadigitaltimes.net/chinese/2015/02/%E7%BF%BB%E5%A2%99-ghost-assassin%EF%BC%9A%E7%BF%BB%E5%A2%99%E4%B8%8E%E5%8C%BF%E5%90%8D%E4%B8%8E%E4%BF%A1%E6%81%AF%E5%AE%89%E5%85%A8%E7%A7%91%E6%99%AE%E6%96%87%E9%93%BE%E6%8E%A5%E9%9B%86%E5%90%88 https://startpage.com file:///mnt/1/%E7%BF%BB%E5%A2%99%20%20%20Shadowsocks%20%E4%BB%8E%E9%9B%B6%E5%BC%80%E5%A7%8B%E4%B8%80%E7%AB%99%E5%BC%8F%E7%BF%BB%E5%A2%99%E6%95%99%E7%A8%8B%20-%20%E4%B8%AD%E5%9B%BD%E6%95%B0%E5%AD%97%E6%97%B6%E4%BB%A3.html https://github.com/greatfire/wiki https://cdt.global.ssl.fastly.net/chinese/2015/02/%E7%BF%BB%E5%A2%99-%E5%85%8D%E8%B4%B9%E7%BF%BB%E5%A2%99%E8%B4%A6%E5%8F%B7%E7%BD%91%E7%AB%99%E5%A4%A7%E9%9B%86%E5%90%88/
